#!/usr/bin/env python

from base.logger import logging
from optimizer import optimize_regressor

if __name__ == "__main__":
    try:
        optimize_regressor()
    except Exception as err:
        logging.error(err)
        raise err