logs_directory_path: logs/
interim_directory_path: data/interim/
data_raw_conexoes_path: data/raw/conexoes_espec.csv
data_raw_individuos_path: data/raw/individuos_espec.csv
model_preprocessor_path: model/preprocessor.pickle
model_regressor_path: model/regressor.pickle
