model: lightgbm

static_parameters:
  #eval_metric: rmse
  #early_stopping_rounds: 200
  random_state: null

opt_config:
  n_folds: 5
  n_calls: 100
  n_random_starts: 1
  verbose: 1
  random_state: null

fit_parameters:
  #verbose: 0
  eval_metric: rmse
  #early_stopping_rounds: 200

cv_optmize_sample: 10000

parametric_space_path: model/lightgbm/config.json
